window.AMULET_QUESTIONS = [
  {
    key: 'q1Wish',
    label: 'שאלה 1',
    tag: '[בקשה]',
    text: 'מה תרצה לבקש?',
    description:
      'כתבו את הדבר שאתם הכי רוצים שיקרה, שיתגשם, שתחוו, מה שמעסיק אתכם כרגע. הבקשה יכולה להיות גדולה או קטנה, קונקרטית או מופשטת בכל נושא שתרצו.',
    type: 'textarea',
    placeholderExamples: [
      'הלוואי שאמצא אהבה',
      'לטוס לתאילנד באוגוסט',
      'למצוא עבודה שאני באמת אוהב',
      'שאצליח להרגיש יותר בטוחה בעצמי.',
      'שהמשפחה שלי תהיה בריאה.',
      'שאפסיק לפחד ממה שיקרה בעתיד.',
    ],
  },
  {
    key: 'q2Name',
    label: 'שאלה 2',
    tag: '[שייכות]',
    text: 'איך קוראים לך?',
    description:
      'כתבו את השם שתרצו שהקמע יישא איתו. זה יכול להיות השם שלכם, כינוי, שם אהוב או כל מילה שמרגישה אישית עבורכם.',
    figmaTitleOffset: true,
    type: 'text',
    placeholder: 'מאיה',
    placeholderExamples: [
      'מאיה',
      'הילה',
      'נועם',
      'שירה',
      'דוד',
      'יעל',
    ],
  },
  {
    key: 'q3WhyNow',
    label: 'שאלה 3',
    tag: '[רגע]',
    text: 'למה דווקא עכשיו?',
    type: 'textarea',
    placeholder: 'לדוגמה: סוף סוף מרגיש/ה מוכן/ה',
  },
  {
    key: 'q4Belief',
    label: 'שאלה 4',
    tag: '[אמונה]',
    text: 'מה הכי גורם לך להאמין שזה אפשרי?',
    type: 'choice',
    options: [
      { value: 'concrete_actions', label: 'המעשים שאני עושה' },
      { value: 'signs', label: 'סימנים וצירופי מקרים' },
      { value: 'gut', label: 'תחושת בטן' },
      { value: 'support', label: 'תמיכה מאנשים סביבי' },
      { value: 'doubt', label: 'אני עדיין לא מאמין שזה אפשרי', fitWidth: true },
    ],
  },
  {
    key: 'q5Feeling',
    label: 'שאלה 5',
    tag: '[תחושה]',
    text: 'איזו תחושה הכי נוכחת סביב הבקשה?',
    type: 'choice',
    options: [
      { value: 'hope', label: 'תקווה' },
      { value: 'fear', label: 'פחד' },
      { value: 'longing', label: 'געגוע' },
      { value: 'excitement', label: 'התרגשות' },
      { value: 'impatience', label: 'חוסר סבלנות' },
      { value: 'confusion', label: 'בלבול' },
    ],
  },
  {
    key: 'q6Difficulty',
    label: 'שאלה 6',
    tag: '[קושי]',
    text: 'מה הכי חסר לך כרגע?',
    type: 'choice',
    options: [
      { value: 'uncertainty', label: 'ביטחון' },
      { value: 'waiting', label: 'הצלחה' },
      { value: 'letting_go', label: 'תשובה' },
      { value: 'failure', label: 'שליטה' },
      { value: 'no_control', label: 'שקט' },
      { value: 'decision', label: 'זמן' },
    ],
  },
  {
    key: 'q7Change',
    label: 'שאלה 7',
    tag: '[שינוי]',
    text: 'אם הבקשה תתגשם, מה באמת ישתנה?',
    figmaTitleOffset: true,
    type: 'textarea',
    placeholder: 'לדוגמה: אהיה פחות לבד בערבים',
  },
  {
    key: 'q8Motivation',
    label: 'שאלה 8',
    tag: '[מוטיבציה]',
    text: 'מה נותן לך ביטחון?',
    description:
      'כתבו מה עוזר לך להאמין שהבקשה שלך אפשרית.',
    type: 'textarea',
    placeholder: 'לדוגמה: כשאני רואה התקדמות קטנה',
  },
];
